---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: busybox

inputs:
  - name: repo
    path: .

outputs:
  - name: version

run:
  path: sh
  args:
    - -exc
    - |-
      cp .git/short_ref version/version
