---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: busybox

outputs:
  - name: version

run:
  path: sh
  args:
    - -exc
    - |
      echo "latest" > version/version
